config/routes.rb
Accepted::Application.routes.draw do
  

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def profile
    @title = "Profile"
  end

  def sign_in
    @title = "Sign In"
  end

  def about
    @title = "About"
  end
  
end


# "@variable" is an instance variable linking actions and views

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@title = "Sign up"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def logo
	image_tag('SqCompFM_logo.png', :alt => "Sample App", :class => "round")
  end



  # Return a title on a per-page basis.
  def title
    
    base_title = "theAccepted.org"
    
    if @title.nil?
    	base_title
    
    else
    	"#{base_title} | #{@title}"
    
    end #end if/else

  end #end def title

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="">Some Other Link</a></li>
			<li><a href="">Some Other Link</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="">Some Other Link</a></li>
			<li><a href="">Some Other Link</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.erb
<header>
	<!-- this does not work - syntax error - look up solution -->
	<!--% logo = image_tag("SqCompFM_logo.png", alt: => "Masonic Logo") % -->
	<%= link_to logo, root_path %>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<!--% if signed_in? %>
			<li><!--%= link_to "Sign out", signout_path, :method => :delete %></li>
			<!--% else %>
			<li><%= link_to "Sign In", signin_path %></li>
			<!--% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_header.html.erb
<header>
	<!-- this does not work - syntax error - look up solution -->
	<!--% logo = image_tag("SqCompFM_logo.png", alt: => "Masonic Logo") % -->
	<%= link_to logo, root_path %>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<!--% if signed_in? %>
			<li><!--%= link_to "Sign out", signout_path, :method => :delete %></li>
			<!--% else %>
			<li><!--%= link_to "Sign In", signin_path %></li>
			<!--% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<[if lt IE9]>
<script src = "http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<[endif]>

<!-- %= stylesheet_link_tag 'blueprint/screen', :media => 'screen' % -->
<!-- %= stylesheet_link_tag 'blueprint/print', :media => 'print' % -->

<!--[if lt IE 8]>
<!--%= stylesheet_link_tag 'blueprint/ie' %-->
<!--[endif]-->

<!--%= stylesheet_link_tag 'custom', :media => 'screen' %-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= @base_title %></title>
  	<%= csrf_meta_tag %> <!-- #prevents cross-site request forgery -->
  	<%= render 'layouts/stylesheets' %>
  </head>
  <body>
  	<div class="container">
		<%= render 'layouts/header' %>
		<section> 
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %> </div>
				<% end %>	
  			<%= yield %>  <!--# see notes below... -->
  		</section>
  		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>	
  </body>
</html>


<!--# the "yield" line above (line 8 as of this note) inserts the contents of each page into the layout -->

app/views/pages/about.html.erb
<h1>theAccepted.org</h1>
<p>This is the about page for theAccepted.org</p>

app/views/pages/contact.html.erb
<h1>theAccepted.org</h1>
<p>This is the contact page for theAccepted.org</p>

app/views/pages/help.html.erb
<h1>theAccepted.org</h1>
<p>This is the help page for theAccepted.org</p>

app/views/pages/home.html.erb
<h1>theAccepted.org</h1>

<p>This is the home page for theAccepted.org</p>


<% link_to "Sign up now!", signup_path %>

app/views/pages/profile.html.erb
<h1>theAccepted.org</h1>
<p>This is the profile page for theAccepted.org</p>

app/views/pages/sign_in.html.erb
<!-- DO NOT USE THE PAGE ???? -->
<!-- IF SIGN IN FROM HOME PAGE FAILS, JUST RELOAD WITH ERRROR MESSAGE -->

<h1>theAccepted.org</h1>
<p>This is the sign in page for theAccepted.org</

app/views/pages/signin.html.erb
<!-- DO NOT USE THE PAGE ???? -->
<!-- IF SIGN IN FROM HOME PAGE FAILS, JUST RELOAD WITH ERRROR MESSAGE -->

<h1>theAccepted.org</h1>
<p>This is the sign in page for theAccepted.org</

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>